{% set name = "lbprodrun" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbProdRun-{{ version }}.tar.gz
  sha256: 2d03c0cf2f1a15fdeca36e3c9bf11ec4f377af01d522acc83e997150534b47e2

build:
  number: 0
  noarch: python
  entry_points:
    - lb-prod-run = LbProdRun.__main__:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - click >=8.0
    - lbenv
    - pydantic >=1.10
    - typer >=0.4.1
    - packaging
    - pyyaml >=6.0

test:
  imports:
    - LbProdRun
  commands:
    - pip check
    - lb-prod-run --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/lbprodrun
  summary: CLI for running LHCb applications from LHCbDIRAC
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
