{% set name = "lbprodrun" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d488080f685f268ad0e1e8b12ed1de3bba973e72396c15e73d7e0208ba40cf43

build:
  number: 0
  noarch: python
  entry_points:
    - lb-prod-run = LbProdRun.__main__:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0
    - lbenv
    - pydantic >=1.10
    - typer >=0.4.1
    - packaging
    - pyyaml >=6.0
    - lbcondawrappers

test:
  imports:
    - LbProdRun
  commands:
    - pip check
    - lb-prod-run --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-core/lbprodrun
  summary: CLI for running LHCb applications from LHCbDIRAC
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
